#!/bin/bash
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-4.7]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-4.7-bin.zip
    unzip gradle-4.7-bin.zip
    rm -f gradle-4.7-bin.zip
fi